#
# This test file has been generated by kwb.test::createTestFiles()
#

test_that("create_test_files() works", {

  # try() manually inserted!
  try(create_test_files())
})

test_that("get_test_codes_for_functions_in_file() works", {

  expect_error(kwb.test:::get_test_codes_for_functions_in_file())
})

test_that("get_test_for_function_assignment() works", {

  expect_error(kwb.test:::get_test_for_function_assignment())
})

test_that("get_templates() works", {

  kwb.test:::get_templates()
})

test_that("runs_without_arguments() works", {

  expect_error(kwb.test:::runs_without_arguments())
})

