# get_test_for_function_calls --------------------------------------------------
#' @importFrom kwb.utils collapsed getAttribute resolve
get_test_for_function_calls <- function(
    call_strings, fun_name, pkg_name, exported
)
{
  templates_raw <- get_templates()

  # Remove the calls that generate the same error messages as previous calls
  fail_indices <- which_calls_fail(call_strings, dbg = FALSE)

  success_indices <- setdiff(seq_along(call_strings), fail_indices)

  fail_indices <- remove_duplicated_fails(fail_indices)

  errors <- kwb.utils::getAttribute(fail_indices, "errors")

  errors <- sapply(errors, get_error_message)

  full_fun_name <- kwb.utils::resolve(
    ifelse(exported, "pkg_fun_exported", "pkg_fun_private"),
    templates_raw,
    fun = fun_name,
    pkg = pkg_name
  )

  pattern <- paste0("(^|\\s)", full_fun_name, "\\(")

  use_shortcut <- function(x) gsub(pattern, "f(", x)

  expect_calls_fail <- sapply(seq_along(fail_indices), function(i) {

    kwb.utils::resolve(
      "fun_call_error",
      templates_raw,
      fun_call = use_shortcut(call_strings[fail_indices[i]]),
      quoted_error = gsub("\n", "\n# ", errors[i])
    )
  })

  expect_calls_success <- sapply(success_indices, function(i) {

    kwb.utils::resolve(
      "fun_call_alone",
      templates_raw,
      fun_call = use_shortcut(call_strings[i])
    )
  })

  #call_strings[fails] <- sprintf("expect_error(%s)", call_strings[fails])
  #test_that_body <- paste0("  ", call_strings, collapse = "\n")

  shortcut <- get_shortcut_assignment(templates_raw, fun_name, pkg_name)

  test_that_body <- paste0(
    "  ", shortcut, "\n\n",
    kwb.utils::collapsed(c(expect_calls_success, expect_calls_fail))
  )

  test_that_call <- kwb.utils::resolve(
    "test_that_call",
    templates_raw,
    fun = fun_name,
    #pkg = pkg_name,
    #pkg_fun = "f", #ifelse(exported, "<pkg_fun_exported>", "<pkg_fun_private>"),
    test_that_body = paste0(test_that_body, "\n")
  )

  structure(test_that_call, fun_name = fun_name)
}

# get_templates ----------------------------------------------------------------
get_templates <- function()
{
  templates <- list(
    intro = "<intro_1>\n<intro_2>\n<intro_3>\n<intro_4>",
    intro_1 = "#\n# This test file has been generated by <test_creator>",
    intro_2 = "# launched by user <user> on <datetime>.",
    intro_3 = "# Your are strongly encouraged to modify the dummy functions",
    intro_4 = "# so that real cases are tested. <hint_delete>\n#\n",
    hint_delete = "You should then delete this comment.",
    test_creator = "kwb.test::create_test_files()",
    test_that_call = "test_that(\"<fun>() works\", {\n\n<test_that_body>})",
    fun_call = "<pkg_fun>(<args>)",
    fun_call_alone = "  <fun_call>\n",
    fun_call_error = "<i1>expect_error(\n<expect_error_args>\n<i1>)\n",
    expect_error_args = "<i2><fun_call>\n<i2># <quoted_error>",
    fun_call_message = "<i1>expect_message(<fun_call>)\n",
    fun_call_silent = "<i1>expect_silent(<fun_call>)\n,",
    pkg_fun_exported = "<fun>",
    pkg_fun_private = "<pkg>:::<fun>",
    i2 = "<i1><i1>",
    i1 = "  "
  )
}

# which_calls_fail -------------------------------------------------------------
which_calls_fail <- function(call_strings, dbg = TRUE)
{
  results <- lapply(call_strings, function(call_string) {

    tryCatch(eval_text(call_string, dbg), error = identity)
  })

  is_error <- sapply(results, inherits, "simpleError")

  structure(which(is_error), errors = results[is_error])
}

# eval_text --------------------------------------------------------------------
#' @importFrom kwb.utils catAndRun
eval_text <- function(text, dbg = TRUE)
{
  kwb.utils::catAndRun(paste0("Evaluating:\n ", text, "\n"), dbg = dbg, {
    eval(parse(text = text))
  })
}

# remove_duplicated_fails ------------------------------------------------------
#' @importFrom kwb.utils getAttribute
remove_duplicated_fails <- function(fails)
{
  errors <- kwb.utils::getAttribute(fails, "errors")

  keep <- !duplicated(sapply(errors, get_error_message))

  structure(fails[keep], errors = errors[keep])
}

# get_error_message ------------------------------------------------------------
get_error_message <- function(error)
{
  if (inherits(error, "error")) {

    error$message

  } else {

    error
  }
}

# get_shortcut_assignment ------------------------------------------------------
get_shortcut_assignment <- function(templates, fun_name, pkg_name)
{
  sprintf(
    "f <- %s",
    kwb.utils::selectElements(
      kwb.utils::resolve(templates, fun = fun_name, pkg = pkg_name),
      ifelse(pkg_name == "", "pkg_fun_exported", "pkg_fun_private")
    )
  )
}
