# get_test_for_function_calls --------------------------------------------------
#' @importFrom kwb.utils collapsed getAttribute resolve
get_test_for_function_calls <- function(
    pkg_name, fun_name, exported = FALSE, arg_strings = ""
)
{
  templates <- get_templates()

  # Create function call strings
  call_strings <- unname(sapply(arg_strings, function(x) {
    kwb.utils::resolve(
      "fun_call",
      templates,
      args = x,
      pkg_fun = "<pkg_fun_private>",
      pkg = pkg_name,
      fun = fun_name
    )
  }))

  # Remove the calls that generate the same error messages as previous calls
  fail_indices <- which_calls_fail(call_strings, dbg = FALSE)

  success_indices <- setdiff(seq_along(arg_strings), fail_indices)

  fail_indices <- remove_duplicated_fails(fail_indices)

  errors <- sapply(
    X = kwb.utils::getAttribute(fail_indices, "errors"),
    FUN = get_error_message
  )

  expect_calls_fail <- sapply(seq_along(fail_indices), function(i) {
    kwb.utils::resolve(
      "fun_call_error",
      templates,
      pkg_fun = "f",
      args = arg_strings[fail_indices[i]],
      quoted_error = gsub("\n", "\n# ", errors[i])
    )
  })

  expect_calls_success <- sapply(success_indices, function(i) {
    kwb.utils::resolve(
      "fun_call_alone",
      templates,
      pkg_fun = "f",
      args = arg_strings[i]
    )
  })

  test_that_body <- sprintf(
    "  f <- %s\n\n%s\n",
    full_function_name(pkg_name, fun_name, exported),
    kwb.utils::collapsed(c(expect_calls_success, expect_calls_fail))
  )

  test_that_call <- kwb.utils::resolve(
    "test_that_call",
    templates,
    fun = fun_name,
    test_that_body = test_that_body
  )

  structure(test_that_call, fun_name = fun_name)
}

# get_templates ----------------------------------------------------------------
get_templates <- function()
{
  templates <- list(
    intro = "<intro_1>\n<intro_2>\n<intro_3>\n<intro_4>",
    intro_1 = "#\n# This file was generated by kwb.test::create_test_files(), ",
    intro_2 = "# launched by <user> on <datetime>.",
    intro_3 = "# Please modify the dummy functions so that real cases are",
    intro_4 = "# tested. Then, delete this comment.\n#\n",
    test_that_call = "test_that(\"<fun>() works\", {\n\n<test_that_body>})",
    fun_call = "<pkg_fun>(<args>)",
    fun_call_alone = "  <fun_call>\n",
    fun_call_error = "<i1>expect_error(\n<expect_error_args>\n<i1>)\n",
    expect_error_args = "<i2><fun_call>\n<i2># <quoted_error>",
    fun_call_message = "<i1>expect_message(<fun_call>)\n",
    fun_call_silent = "<i1>expect_silent(<fun_call>)\n,",
    pkg_fun_exported = "<fun>",
    pkg_fun_private = "<pkg>:::<fun>",
    i2 = "<i1><i1>",
    i1 = "  "
  )
}

# get_full_function_name -------------------------------------------------------
get_full_function_name <- function(
    fun_name,
    pkg_name,
    exported = fun_name %in% getNamespaceExports(pkg_name)
)
{
  kwb.utils::resolve(
    ifelse(exported, "pkg_fun_exported", "pkg_fun_private"),
    get_templates(),
    fun = fun_name,
    pkg = pkg_name
  )
}

# which_calls_fail -------------------------------------------------------------
which_calls_fail <- function(call_strings, dbg = TRUE)
{
  results <- lapply(call_strings, function(call_string) {
    tryCatch(eval_text(call_string, dbg), error = identity)
  })

  is_error <- sapply(results, inherits, "simpleError")

  structure(which(is_error), errors = results[is_error])
}

# eval_text --------------------------------------------------------------------
#' @importFrom kwb.utils catAndRun
eval_text <- function(text, dbg = TRUE)
{
  kwb.utils::catAndRun(paste0("Evaluating:\n ", text, "\n"), dbg = dbg, {
    suppressWarnings(eval(parse(text = text)))
  })
}

# remove_duplicated_fails ------------------------------------------------------
#' @importFrom kwb.utils getAttribute
remove_duplicated_fails <- function(fails)
{
  errors <- kwb.utils::getAttribute(fails, "errors")

  keep <- !duplicated(sapply(errors, get_error_message))

  structure(fails[keep], errors = errors[keep])
}

# get_error_message ------------------------------------------------------------
get_error_message <- function(error)
{
  if (inherits(error, "error")) {

    error$message

  } else {

    error
  }
}

# full_function_name -----------------------------------------------------------
full_function_name <- function(pkg_name, fun_name, exported)
{
  paste0(pkg_name, ifelse(exported, "::", ":::"), fun_name)
}
